export enum BOARD_SOCKET_MESSAGES {
  AddUser = 'user_add',
  LeaveBoard = 'board_leave',
  DeleteBoard = 'board_delete',
  ChangeBoardTitle = 'board_title',
  ChangeBoardDescription = 'board_description',
  AddList = 'list_add',
  ChangeListTitle = 'list_title',
  ChangeListPosition = 'list_position',
  DeleteList = 'list_delete',
  AddCard = 'card_add',
  ChangeCardTitle = 'card_title',
  ChangeCardDescription = 'card_description',
  ChangeCardPosition = 'card_position',
  AssignCardUser = 'card_user',
  DeleteCard = 'card_delete',
}
